import { montserrat } from "@/libs/fonts";
import "../styles/globals.css";

export const metadata = {
	title: {
		template: "%s | Arya",
		default: "Arya", // a default is required when creating a template
	},
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr">
			<body className={montserrat.className}>{children}</body>
		</html>
	);
}
