import { montserrat } from "@/libs/fonts";
import "../styles/globals.css";
import Header from "@/layouts/Header";
import Footer from "@/layouts/Footer";

export const metadata = {
	title: {
		template: "%s | Arya",
		default: "Arya", // a default is required when creating a template
	},
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr">
			<body className={montserrat.className}>
				<Header />
				{children}
				{/* <Footer /> */}
			</body>
		</html>
	);
}
