const spamKeywords = [
	"gratuit",
	"100% gratuit",
	"remboursé",
	"cadeau",
	"appel gratuit",
	"pas de frais",
	"inscription gratuite",
	"essai gratuit",
	"Aaccès gratuit",
	"gratuitement",
	"réduction",
	"rabais",
	"meilleur prix",
	"promotion",
	"promotion spéciale",
	"offre spéciale",
	"comparer les prix",
	"pour seulement",
	"pas cher",
	"abordable",
	"coût",
	"coupon",
	"50%",
	"faites vite",
	"urgent",
	"profitez maintenant",
	"offre limitée",
	"dès maintenant",
	"dès aujourd’hui",
	"n’hésitez plus",
	"appelez maintenant",
	"expire",
	"temps limité",
	"durée limitée",
	"quantités limitées",
	"rupture de stock",
];

module.exports = spamKeywords;
