const spamKeywords = [
	"gratuit",
	"100% gratuit",
	"remboursé",
	"cadeau",
	"appel gratuit",
	"pas de frais",
	"inscription gratuite",
	"essai gratuit",
	"accès gratuit",
	"gratuitement",
	"réduction",
	"rabais",
	"meilleur prix",
	"promotion",
	"promotion spéciale",
	"offre spéciale",
	"comparer les prix",
	"pour seulement",
	"pas cher",
	"abordable",
	"coût",
	"coupon",
	"50%",
	"faites vite",
	"urgent",
	"profitez maintenant",
	"offre limitée",
	"dès maintenant",
	"dès aujourd’hui",
	"n’hésitez plus",
	"appelez maintenant",
	"expire",
	"temps limité",
	"durée limitée",
	"quantités limitées",
	"rupture de stock",
	"vous avez gagné",
	"bravo",
	"ouvrez pour découvrir votre cadeau",
	"cadeau exceptionnel",
	"gagnant",
	"vous avez été choisi",
	"félicitations",
	"récompense",
	"pour vous seulement",
	"garanti",
	"100% garanti",
	"100% sûr",
	"certifié",
	"sans risque",
	"deal incroyable",
	"bonus",
	"bonne affaire",
	"vu à la TV",
	"deal",
	"ça fonctionne",
	"satisfaction garantie",
	"pas d’arnaque",
	"pas un spam",
	"identité",
	"mot de passe",
	"pas de coûts cachés",
	"aucun risque",
	"cash",
	"money",
	"facile",
	"argent rapide",
	"gagner de l’argent",
	"revenu supplémentaire",
	"bénéfice",
	"millions de dollars",
	"économiser",
	"meilleur prix",
	"euros",
	"profits",
	"gains",
	"votre propre patron",
	"carte de crédit",
	"carte bancaire",
	"investissement",
	"faillite",
	"revenu",
	"salaire",
	"taux d’intérêt",
	"assurance",
	"sortir des dettes",
	"remboursement",
	"remboursement intégral",
	"chèque",
	"virement bancaire",
	"débit",
	"hypothèque",
	"paypal",
	"prime",
	"rendement",
	"visa",
	"mastercard",
	"ventes",
	"soldes",
	"augmentez vos ventes",
	"augmentez votre trafic",
	"cliquez ici",
	"commande",
	"plus de ventes",
	"chiffre d’affaires",
	"marketing",
	"acheter",
	"augmentez",
	"#1",
	"100% more",
	"100% free",
	"100% satisfied",
	"additional income",
	"be your own boss",
	"best price",
	"big bucks",
	"billion",
	"cash bonus",
	"cents on the dollar",
	"consolidate debt",
	"double your cash",
	"double your income",
	"earn extra cash",
	"earn money",
	"eliminate bad credit",
	"extra cash",
	"extra income",
	"expect to earn",
	"fast cash",
	"financial freedom",
	"free access",
	"free consultation",
	"free gift",
	"free hosting",
	"free info",
	"free investment",
	"free membership",
	"free money",
	"free preview",
	"free quote",
	"free trial",
	"full refund",
	"get out of debt",
	"get paid",
	"giveaway",
	"guaranteed",
	"increase sales",
	"increase traffic",
	"incredible deal",
	"lower rates",
	"lowest price",
	"make money",
	"million dollars",
	"miracle",
	"money back",
	"once in a lifetime",
	"one time",
	"pennies a day",
	"potential earnings",
	"prize",
	"promise",
	"pure profit",
	"risk-free",
	"satisfaction guaranteed",
	"save big money",
	"save up to",
	"special promotion",
	"act now",
	"apply now",
	"become a member",
	"call now",
	"click below",
	"click here",
	"get it now",
	"do it today",
	"don’t delete",
	"exclusive deal",
	"get started now",
	"important information regarding",
	"information you requested",
	"instant",
	"limited time",
	"new customers only",
	"order now",
	"please read",
	"see for yourself",
	"sign up free",
	"take action",
	"this won’t last",
	"urgent",
	"what are you waiting for?",
	"while supplies last",
	"will not believe your eyes",
	"winner",
	"winning",
	"you are a winner",
	"you have been selected",
	"Bulk email",
	"Buy direct",
	"Cancel at any time",
	"Check or money order",
	"Congratulations",
	"Confidentiality",
	"Cures",
	"Dear friend",
	"Direct email",
	"Direct marketing",
	"Hidden charges",
	"Human growth hormone",
	"Internet marketing",
	"Lose weight",
	"Mass email",
	"Meet singles",
	"Multi-level marketing",
	"No catch",
	"No cost",
	"No credit check",
	"No fees",
	"No gimmick",
	"no hidden costs",
	"No hidden fees",
	"No interest",
	"No investment",
	"No obligation",
	"No purchase necessary",
	"No questions asked",
	"No strings attached",
	"Not junk",
	"Notspam",
	"Obligation",
	"Passwords",
	"Requires initial investment",
	"Social security number",
	"This isn’t a scam",
	"This isn’t junk",
	"This isn’t spam",
	"Undisclosed",
	"Unsecured credit",
	"Unsecured debt",
	"Unsolicited",
	"Valium",
	"Viagra",
	"Vicodin",
	"We hate spam",
	"Weight loss",
	"Xanax",
];

module.exports = spamKeywords;
